const strings = {
    text1:"Sign in",
    text2:"with your valid credentials",
    Forget:"Forget Password",
    Primary:"Primary",
    Reset:"Reset your password with just a few clicks",
    send_link:'Send Link',
    Reset_password:"Reset Password",
    Enter:"Enter in your new password",
    continue:"Continue",
    welcome:"Welocome",
    kevin:"Kevin",
    get_started:"Get Started",
    secure:"Secure your Account ?",
    secure_setup:"setup two-factor authentication to secure ",
    secure_setup1:"your account in just two steps.",
    link:"Link your account with your phone ",
    enter_the:"Enter the one-time passcode",
    secure_your:"Secure your account",
    add_phone:"Add Phone Number",
    To_initiate:"To initiate the two-factor authentication,",
    To_initiate1:"provide your phone number below.",
    send_code:"Send Code",
    verify:"Verify Account Access",
    Enter_the:"Enter the verification code sent to",
    Phone_number:"+1-788-895-5435",
    Confirm_code:"Confirm Code",
    resend:"Resend",
    submit:"Submit",
    Account_Locked:"Account Locked",
    your_account:"your account has been locked due to",
    Too_many:"too many failed attempts .please try",
    again_after:"again after some time",
    ok:"Okay",
    link_sent:"Link sent!",
    The_link:"The link to reset your password has  ",
    been_sent:"been sent on your email.address",
    Complete:"Complete your account setup",
    Tap:"Tap to continue",
    Frequently:"FREQUENTLY USED",
    Resent_activities:"RECENT ACTIVITIES",
    All_Product:"All product ⌄",
    successfully:"Sucessfully configured POS for sites",
    date:"Jun 3, 2023 | 12:30 PM"
  };
  
  export default strings;